services:
  _defaults:
    autowire: true
    autoconfigure: true

  Optime\TimeZone\Bundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/OptimeTimeZoneBundle.php'